services:
  - type: web
    name: rag-toy-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: OPENSEARCH_HOST
        sync: false
      - key: OPENSEARCH_USER
        sync: false
      - key: OPENSEARCH_PASSWD
        sync: false
      - key: OPENSEARCH_PORT
        sync: false
      - key: OPENSEARCH_INDEX
        sync: false
      - key: CLOVA_API_TOKEN
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
